# Generated by Django 4.1.2 on 2023-07-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='assigned_issues',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='issue',
            name='agentId',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='issue',
            name='mechanicId',
            field=models.IntegerField(default=None),
        ),
    ]
