# Generated by Django 4.1.2 on 2023-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_agents_assigned_issues_issue_agentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='agentId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='mechanicId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
