# Generated by Django 4.1.2 on 2023-07-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_issue_agentid_alter_issue_mechanicid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='assigned_issues',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
