# Generated by Django 4.1.2 on 2023-07-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_agents_assigned_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('INQUEUE', 'In Queue'), ('ASSIGNED', 'Assigned'), ('DISPATCHED', 'Dispatched'), ('RESOLVED', 'Resolved')], max_length=20),
        ),
    ]
